#debug: true
server:
  port: 8222
spring:
  r2dbc:
    name: sa
    password: welcome
    url: r2dbc:h2:mem:///orders_db
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    include: h2
app:
  h2-console-port: 8081
