DROP TABLE IF EXISTS orders;
CREATE TABLE orders(
    order_id INT Generated by default  as identity  primary key,
    email varchar (45) not null,
    name varchar (45) not null,
    order_date date not null
);